name: Staging Deploy

on:
  push:
    branches:
      - staging

jobs:
  build_push_to_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setub Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Bump version and push tag
        id: tagger
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: New version
        run: yarn version -i ${{ steps.tagger.outputs.new_tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: gustavisk/guinaweb-staging
          tags: ${{ steps.tagger.outputs.new_tag }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          
      - name: Push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gustavisk/guinaweb-staging

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build_push_to_hub
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            sudo systemctl restart guinaweb-staging.service
            exit
